# Generated by Django 6.0.7 on 2026-08-03 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0002_remove_doctor_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='available_days',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
